const LABEL_PS = [
    { opA: '.A' },
    { opB: '.B' },
    { opC: '.C' },
    { opD: '.D' },
    { buyPackages: 'د کڅوړو اخیستل' },
    { expiryOn: 'د ختمېدو نېټه' },
    { price: 'قیمت' },
    { aPPLY: 'غوښتنه وکړئ' },
    { havePromo: 'تبلیغاتي کوډ لرئ؟' },
    { haveScratch: 'سکریچکارډ لرئ؟' },
    { PROCEED: 'مخته ځئ' },
    { proceedToPay: 'د تادیې لپاره مخ ته لاړ شئ' },
    { GST: 'GST د خدمتونو مالیات' },
    { promoDis: 'تبلیغاتي تخفیف ' },
    { scratchApplied: 'کریډیټ کارټ قبول شو' },
    { gowith: '...مخ کې لاړ شئ' },
    { startNew: 'د نوې ازمویني پیل کول' },
    { reviewTest: 'تېرې آزموینې بیاکتنه' },
    { contactUs: 'له موږ سره اړیکه' },
    { profile: 'پروفایل' },
    { notification: 'خبرتیا' },
    { buyPackages: 'د کڅوړو پیرودل' },
    { refer: 'مراجعه وکړئ او ترلاسه کړئ' },
    { myWallet: 'زما شخصي حساب' },
    { logout: 'وتل' },
    { welcome: 'ښه راغلاست' },
    { forgetPass: 'خپل رمز مو هیر کړی؟' },
    { submit: 'سپارل' },
    { selectGrade: 'ټولګی مو وټاکئ' },
    { signUp: 'حساب نلرئ ؟ نوم لیکنه وکړئ' },
    { forgotPass: 'خپل رمز درڅخه هیر دی؟' },
    { name: 'نوم' },
    { email: 'برېښنالیک' },
    { moNumber: 'د موبایل 10 رقمي شمېره' },
    { password: 'د ننوتلو رمز' },
    { cPassword: 'د رمز تایید' },
    { CONFIRM: 'تایید' },
    { CANCEL: 'لغوه' },
    { selectGrades: 'خپل ټولګی مو وټاکئ' },
    { gradeNotAvailabel: 'ټولګي شتون نلري' },
    { citiesNotAvilable: 'ښارونه شتون نلري' },
    { city: 'ښار' },
    { grade: 'ټولګی' },
    { board: 'نصاب' },
    { mobileNumber: 'ګرځنده شمیره' },
    { selectDate: 'نېټه وټاکئ' },
    { name: 'نوم' },
    { profileCompletion: 'د پېژندڅېرې یا پروفایل بشپړول' },
    { profileDetails: 'د پروفایل توضیحات' },
    { questions: 'پوښتنې' },
    { correct: 'سم' },
    { test: 'آزموینه' },
    { attempted: 'هڅه ترسره شوه' },
    { avgTime: 'اوسط وخت' },
    { question: 'پوښتنه' },
    { easy: 'اسانه' },
    { medium: 'منځینی' },
    { hard: 'سخت' },
    { performance: 'کړنه' },
    { needFocus: ':باید لاندې موضوګانو ته پاملرنه وکړئ' },
    { overall: 'په ټوله کی ' },
    { practice: 'تمرین' },
    { summary: 'لنډیز' },
    { correct: 'سم' },
    { incorrect: 'ناسم' },
    { axes: 'X->پوښتنې, Y->وخت په ثانیه' },
    { VIEWSOLUTION: 'د پوښتنو حل وګورئ' },
    { Score: 'نمره' },
    { lightningFast: 'تاسو د رعد او برق په څیر یاست' },
    { perfect: 'بشپړ' },
    { slowGoing: 'تاسو ضعیف یاست' },
    { Incorrect: 'ناسم' },
    { statistics: 'شمیرې' },

    { loadingContent: 'محتوا باریږئ هیله کوم منتظر پاتي شئ' },
    { chooseLanguage: 'خپله ژبه مو وټاکئ' },
    { timeLeft: 'پاتې وخت' },
    { minutes: 'دقیقې' },
    { preAss: 'مخکی له ارزونی څخه' },
    { postAss: 'وروسته له ارزونی څخه' },
    { next: 'بل' },
    { previous: 'تېر' },
    { practice: 'تمرین وکړئ' },
    { myLib: 'زما کتابتون' },
    { teacherResource: 'د ښوونکی سرچینه' },
    { close: 'بند کړئ' },
    { enterotp: 'دننه کړئ OTP' },
    { recommendedTopics: 'اړوند موضوعات' },
    { subjectQuiz: 'د مضمون ازموینه' },

    { start: 'پیل' },
    { preTest: 'د درس څخه مخکی ازموینه' },
    { postTest: 'د درس څخه وروسته ازموینه' },
    { video: 'ویډیو' },
    { notes: 'یادونې' },
    { notification: 'خبرتیا' },
    { inviteFriend: 'ملګري ته مو بلنه ورکړئ' },
    { referFriend: 'د خپل ملګری سره شریک کړئ' },

    { ok: 'سم دی' },
    { okay: 'سم دی' },
    { continue: 'دوام ورکړئ' },
    { interactiveQue: 'متقابله پوښتنه' },
]

export default { LABEL_PS };