const LABEL_DA = [
    { opA: '.A' },
    { opB: '.B' },
    { opC: '.C' },
    { opD: '.D' },
    { buyPackages: 'خریداری بسته ها' },
    { expiryOn: 'تاریخ انقضا' },
    { price: 'قیمت' },
    { aPPLY: 'درخواست کردن' },
    { havePromo: 'کد تبلیغی دارید؟' },
    { haveScratch: 'کارت خراش دارید؟' },
    { PROCEED: 'ادامه دهید' },
    { proceedToPay: 'برای پرداخت ادامه دهید' },
    { GST: 'مالیات خدماتی' },
    { promoDis: 'تخفیف تبلیغاتی' },
    { scratchApplied: 'کریدت کارت پذیرفته شد' },
    { gowith: '...ادامه دهید' },
    { startNew: 'شروع کردن امتحان جدید' },
    { reviewTest: 'مرور امتحان قبلی' },
    { contactUs: 'تماس با ما' },
    { profile: 'پروفایل' },
    { notification: 'تذکر' },
    { buyPackages: 'خریداری بسته ها' },
    { refer: 'شریک سازید و بدست نمائید' },
    { myWallet: 'حساب شخصی من' },
    { contactUs: 'تماس با ما' },
    { logout: 'خروج' },
    { welcome: 'خوش آمدید' },
    { forgetPass: 'رمزتان را فراموش کرده اید؟' },
    { submit: 'آیا مطمئن به درج نمودن ارزیابی هستید' },
    { selectGrade: 'صنف تان را انتخاب کنید' },
    { signUp: 'حساب ندارید؟ ثبت نام نمایید' },
    { forgotPass: 'رمز را فراموش کرده اید؟' },
    { name: 'اسم' },
    { email: 'ایمیل' },
    { moNumber: 'شماره تماس' },
    { password: 'رمز عبور' },
    { cPassword: 'تایید رمز' },
    { CONFIRM: 'تایید' },
    { CANCEL: 'لغو' },
    { selectGrades: 'صنف های تان را انتخاب کنید' },
    { gradeNotAvailabel: 'این صنف در دسترس نیست' },
    { citiesNotAvilable: 'شهر ها در دسترس نیست' },
    { city: 'شهر' },
    { grade: 'صنف' },
    { board: 'نصاب' },
    { mobileNumber: 'شماره تماس' },
    { selectDate: 'تاریخ را انتخاب نمایید' },
    { name: 'اسم' },
    { profileCompletion: 'تکمیل پروفایل' },
    { profileDetails: 'جزئیات پروفایل' },
    { questions: 'سوالات' },
    { correct: 'صحیح' },
    { test: 'امتحان' },
    { attempted: 'کوشش صورت گرفت' },
    { avgTime: 'اوسط زمان' },
    { question: 'سوال' },
    { easy: 'آسان' },
    { medium: 'متوسط' },
    { hard: 'سخت' },
    { performance: 'کارایی' },
    { needFocus: ':به موضوعات ذیل توجه شود' },
    { overall: 'به طور کلی' },
    { practice: 'تمرین' },
    { summary: 'خلاصه' },
    { correct: 'صحیح' },
    { incorrect: 'غلط' },
    { axes: 'X->سوالات}, Y->زمان به ثانیه' },
    { VIEWSOLUTION: 'مشاهده حل سوالات' },
    { Score: 'امتیاز' },
    { lightningFast: 'شما مثل رعد و برق هستید' },
    { perfect: 'کاملاً درست' },
    { slowGoing: 'بسیار ضعیف هستید' },
    { Incorrect: 'غلط' },
    { statistics: 'آمار' },

    { loadingContent: '... محتوا در حال بارگیری است، لطفاً صبر نمایید' },
    { chooseLanguage: 'زبان تان را انتخاب نمایید' },
    { timeLeft: 'زمان باقی مانده' },
    { minutes: 'دقایق' },
    { preAss: 'قبل از ارزیابی' },
    { postAss: 'بعد از ارزیابی' },
    { next: 'بعدی' },
    { previous: 'قبلی' },
    { practice: 'تمرین' },
    { myLib: 'کتابخانه من' },
    { teacherResource: 'منبع معلم' },
    { close: 'بر گشت' },
    { enterotp: 'کود ورود را وارد نمایید' },
    { recommendedTopics: 'موضوعات مرتبط' },
    { subjectQuiz: 'امتحان مضمون' },

    { start: 'شروع' },
    { preTest: 'امتحان قبل از درس' },
    { postTest: 'امتحان بعد از درس' },
    { video: 'ویدیو' },
    { notes: 'متن درس' },
    { notification: 'تذکر' },
    { inviteFriend: 'دوست تان را دعوت نمایید' },
    { referFriend: 'با دوست تان شریک سازید' },

    { ok: 'درست' },
    { okay: 'درست' },
    { continue: 'ادامه دهید' },
    { interactiveQue: 'سوال متقابل' },
]

export default { LABEL_DA };