const LABEL = {
    opA: 'opA',
    opB: 'opB',
    opC: 'opC',
    opD: 'opD',
    buyPackages: 'buyPackages',
    expiryOn: 'expiryOn',
    price: 'price:',
    aPPLY: 'aPPLY',
    havePromo: 'havePromo',
    haveScratch: 'haveScratch',
    PROCEED: 'PROCEED',
    proceedToPay: 'proceedToPay',
    GST: 'GST',
    promoDis: 'promoDis',
    scratchApplied: 'scratchApplied',
    gowith: 'gowith',
    startNew: 'startNew',
    reviewTest: 'reviewTest',
    contactUs: 'contactUs',
    profile: 'profile',
    notification: 'notification',
    buyPackages: 'buyPackages',
    refer: 'refer',
    myWallet: 'myWallet',
    contactUs: 'contactUs',
    logout: 'logout',
    welcome: 'welcome',
    forgetPass: 'forgetPass',
    submit: 'submit',
    selectGrade: 'selectGrade',
    signUp: "signUp",
    forgotPass: 'forgotPass',
    name: 'name',
    email: 'email',
    moNumber: 'moNumber',
    password: 'password',
    cPassword: 'cPassword',
    CONFIRM: 'CONFIRM',
    CANCEL: 'CANCEL',
    selectGrades: 'selectGrades',
    gradeNotAvailabel: 'gradeNotAvailabel',
    citiesNotAvilable: 'citiesNotAvilable',
    city: 'city',
    grade: 'grade',
    board: 'board',
    mobileNumber: 'e',
    selectDate: 'selectDate',
    name: 'name',
    profileCompletion: 'profileCompletion',
    profileDetails: 'profileDetails',
    questions: 'questions',
    correct: 'correct',
    test: 'test',
    attempted: 'attempted',
    avgTime: 'avgTime',
    question: 'question',
    easy: 'easy',
    medium: 'medium',
    hard: 'hard',
    performance: 'performance',
    needFocus: 'needFocus',
    overall: 'overall',
    practice: 'practice',
    summary: 'summary',
    correct: 'correct',
    incorrect: 'incorrect',
    axes: 'axes',
    VIEWSOLUTION: 'VIEWSOLUTION',
    Score: 'Score',
    lightningFast: 'lightningFast',
    perfect: 'perfect',
    slowGoing: 'slowGoing',
    Incorrect: 'Incorrect',
    statistics: 'statistics',

    loadingContent: 'loadingContent',
    chooseLanguage: 'chooseLanguage',
    timeLeft: 'timeLeft',
    minutes: 'minutes',
    preAss: 'preAss',
    postAss: 'postAss',
    next: 'next',
    previous: 'previous',
    practice: 'practice',
    myLib: 'myLib',
    teacherResource: 'teacherResource',
    close: 'close',
    enterotp: 'enterotp',
    recommendedTopics: 'recommendedTopics',
    subjectQuiz: 'subjectQuiz',

    start: 'start',
    preTest: 'preTest',
    postTest: 'postTest',
    video: 'video',
    notes: 'notes',
    notification: 'notification',
    inviteFriend: 'inviteFriend',
    referFriend: 'referFriend',

    ok: 'ok',
    okay: 'okay',
    continue: 'continue',
    interactiveQue: 'interactiveQue',

    beforeLogin1: 'Loading content, please wait...',
    beforeLogin2: 'Choose Language',

    update: 'update',
}

export default LABEL;