const MESSAGE = {
    otpMsg: 'otpMsg',
    mailSubject: 'mailSubject',
    wentWrong: 'wentWrong',
    invalidGrade: 'invalidGrade',
    invalidTest: 'invalidTest',
    enterEmailOrPass: 'enterEmailOrPass',
    gradeNotEnrolled: 'gradeNotEnrolled',
    gradeAlreadyPurchased: 'gradeAlreadyPurchased',
    noDeviceToken: 'noDeviceToken',
    orderNotGenerated: 'orderNotGenerated',
    selectSems: 'selectSems',
    completeChaps: 'completeChaps',
    enterUserName: 'enterUserName',
    enterPassword: 'enterPassword',
    enterOTP: 'enterOTP',
    invalidOTP: 'invalidOTP',
    invalidPassword: 'invalidPassword',
    passwordNotMatched: 'passwordNotMatched',
    passwordReset: 'passwordReset',
    enterValidName: 'enterValidName',
    enterValidEmail: 'enterValidEmail',
    enterValidMobile: 'enterValidMobile',
    selectState: 'selectState',
    selectCity: 'selectCity',
    selectGrade: 'selectGrade',
    selectBoard: 'selectBoard',
    stateNotAvailable: 'stateNotAvailable',
    boardNotAvailable: 'boardNotAvailable',
    noSubjects: 'noSubjects',
    noQuestions: 'noQuestions',
    noQuestionPaper: 'noQuestionPaper',
    noChapter: 'noChapter',
    noTopic: 'noTopic',
    noGrades: 'noGrades',
    noNotes: 'noNotes',
    noMockTest: 'noMockTest',
    noTest: 'noTest',
    number1: 'number1',
    number2: 'number2',
    emailID: 'emailID',
    emailSubject: 'emailSubject',
    webSite: 'webSite',

    noLanguage: 'noLanguage',
    submitQuiz: 'submitQuiz',
    timeUp: 'timeUp',
    otpMsg1: 'otpMsg1',
    otpMsg2: 'otpMsg2',
    selectState: 'selectState',
    selectBoard: 'selectBoard',
    noNotification: 'noNotification',
    inviteYourFriend: 'inviteYourFriend',
    installApp: 'installApp',
    enjoyLearning: 'enjoyLearning',

    completePreTest: 'completePreTest',
    beginTest: 'beginTest',
    youWillHave: 'youWillHave',
    finishTest: 'finishTest',
    notGraded: 'notGraded',
    areYouReady: 'areYouReady',
    completePostTest: 'completePostTest',
    gradedTest: 'gradedTest',
    scoreIs: 'scoreIs',
    tryAgain: 'tryAgain',
    testAgain: 'testAgain',
    highestScore: 'highestScore',
    correctAns: 'correctAns',
    incorrectAns: 'incorrectAns',

    updateAvailable: 'updateAvailable',
}

export default MESSAGE;