const MESSAGE_PS = [
    { otpMsg: ' OTP زما ښوونکي: داستاسو د نوم ثبتولو کوډ دي' },
    { mailSubject: 'زما ښوونکي:   دننوتلو رمز د یو ځل لپاره' },
    { wentWrong: 'اوبخښئ! کومه ستونزه پېښه شوه' },
    { invalidGrade: 'اوبخښئ! ټولګی ونه موندل شو', },
    { invalidTest: 'اوبخښئ! آزموینه شتون نلري', },
    { enterEmailOrPass: "مهربانی وکړئ د بریښنالیک پته یا ګرځنده شمیره د ننه کړی" },
    { gradeNotEnrolled: 'تاسو د      لپاره نوم لیکنه نده کړې', },
    { gradeAlreadyPurchased: "شما قبلاً خریداری کرده اید" },
    { noDeviceToken: 'دستګاه د ننوتلو کوډ ندی جوړ کړی' },
    { orderNotGenerated: ' وبخښئ ستاسو غوښتل شوي آي ډي نده رامنځ ته شوئ ' },
    { selectSems: '.مهرباني وکړئ مناسب سمسترونه غوره کړئ', },
    { completeChaps: 'د ننه کیدلو لپاره مهربانی وکړی مخکینی فصلونه بشپړ کړۍ' },
    { enterUserName: 'مهرباني وکړئ کارن نوم دننه کړئ', },
    { enterPassword: 'مهربانی وکړۍ پټ نوم د ننه کړۍ' },
    { enterOTP: 'دننه کړئ OTP مهرباني وکړئ' , },
    { invalidOTP: 'دننه کړئ OTP تاسو ناسم', },
    { invalidPassword: 'پټ نوم یا رمز باید لږترلږه 8 رقمونه ولری' },
    { passwordNotMatched: 'رمز سمون نه لري' },
    { passwordReset: 'رمز په بریالیتوب سره تنظیم شو',},
    { enterValidName: 'مهرباني وکړئ سم نوم دننه کړئ',},
    { enterValidEmail: 'مهرباني وکړئ سم ایمیل آدرس دننه کړئ',},
    { enterValidMobile: 'مهربانی وکړئ سمه شمیره د ننه کړئ' },
    { selectCity: 'مهرباني وکړئ ښار غوره کړئ', },
    { selectGrade: 'مهرباني وکړئ ټولګی غوره کړئ', },
    { stateNotAvailable: 'ایالتونه شتون نلري', },
    { boardNotAvailable: 'نصاب شتون نلري', },
    { noSubjects: '!هېڅ موضوع ونه موندل شوه', },
    { noQuestions: '!هېڅ پوښتنه ونه موندل شوه', },
    { noQuestionPaper: "!د پوښتنې هېڅ ورقه ونه موندل شوه", },
    { noChapter: '!هېڅ فصل ونه موندل شو', },
    { noTopic: '!هېڅ موضوع ونه موندل شوه', },
    { noGrades: '!هېڅ ټولګي ونه موندل شوه', },
    { noNotes: '!هیځ متن ونه موندل شوه' },
    { noMockTest: '!هیڅ د آزموینی پوښتنی ونه موندل شوی' },
    { noTest: '!آزمویښتی پوښتنی ونه موندل شوی'  },
    { number1: '9494843456' },
    { number2: '08912702222' },
    { emailID: 'support@smartstepup.com' },
    { emailSubject: 'Inquiry from MyTeacher' },
    { webSite: 'www.smartstepup.com' },

    { noLanguage: '!ژبه ونه موندل شوه' },
    { submitQuiz: 'ایا تاسو ډاډه یاست چې ارزونه وړاندې کړئ؟' },
    { timeUp: 'وخت پای ته ورسېد! مهرباني وکړئ خپله ارزيابي وسپارئ' },
    { otpMsg1: 'موږ تاسو ته د ننوتلو پټ نوم درلیږلی دئ په' },
    { otpMsg2: 'او' },
    { selectState: 'مهربانی وکړئ ایالت مو وټاکۍ' },
    { selectBoard: 'مهرباني وکړئ تعلیمي نصاب وټاکئ' },
    { noNotification: 'نوې خبرتیاوې نشته' },
    { inviteYourFriend: 'خپل ملګري ته مود نوم ليکنې لپاره بلنه ورکړئ' },
    { installApp: 'ستاسو ملګری برنامه نصب کړئ' },
    { enjoyLearning: '!د زده کړی د دوری څخه خوند واخلئ' },

    { completePreTest: 'اوبخښئ! لومړی باید مخکي د درس څخه آزموینه بشپړه کړئ' },
    { beginTest: 'تاسو د آزموینی د پیل کولو په حال کی یاست' },
    { youWillHave: 'یتاسو به د پیل څخه وروسته ولرئ' },
    { finishTest: '10دقیقې د آزموینی د پای ته رسیدو لپاره لرئ' },
    { notGraded: '.ددي ازموینی له مخي درجه بندي نه کیږي' },
    { completePostTest: 'تاسو د درس وروسته د آزموینی د پیل کولو په حال کی یاست' },
    { gradedTest: 'ددي ازمویني له مخي درجه بندي کیږي' },
    { scoreIs: ':ستاسو نمرې دي' },
    { tryAgain: 'اآیا غواړئ بیا هڅه وکړئ؟' },
    { testAgain: 'تاسو کولی شئ بیا هڅه وکړئ.' },
    { highestScore: '.موږ به لوړه نمره وساتو' },
    { correctAns: 'ډېر ښه! ستاسو ځواب سم دی' },
    { incorrectAns: 'موږ به ستاسو لوړه نمره وساتو' },
    { areYouReady: 'ایا تاسو د پیل لپاره چمتو یاست؟' },
]

export default { MESSAGE_PS };