const MESSAGE_DA = [
    { otpMsg: 'این کود ثبت نام شما است' },
    { mailSubject: 'معلم من: کود عبور برای یک بار' },
    { wentWrong: 'ببخشید! مشکلی پیش آمد' },
    { invalidGrade: 'ببخشید! صنف یافت نشد' },
    { invalidTest: 'ببخشید! امتحان در دسترس نیست' },
    { enterEmailOrPass: "لطفاً ایمیل یا شماره تماس تان را وارد نمایید" },
    { gradeNotEnrolled: 'شما برای      ثبت نام نکرده اید' },
    { gradeAlreadyPurchased: "شما قبلاً خریداری نموده اید" },
    { noDeviceToken: 'دستگاه کود عبور را تهیه ننموده است' },
    { orderNotGenerated: 'ببخشید، آی دی درخواست تهیه نگردیده است' },
    { selectSems: 'لطفا سمستر مناسب تان را انتخاب نمایید' },
    { completeChaps: 'برای وررد فصل های قبلی را تکمیل نمایید' },
    { enterUserName: 'لطفاً اسم کاربری را وارد نمایید' },
    { enterPassword: 'لطفاً رمز عبور تان را وارد نمایید' },
    { enterOTP: 'لطفاً کود عبور تان را وارد نمایید' },
    { invalidOTP: 'کود عبور اشتباه است' },
    { invalidPassword: 'رمز عبور باید حد اقل 8 رقم باشد' },
    { passwordNotMatched: 'رمز عبور مطابقت ندارد' },
    { passwordReset: 'رمز عبور با موفقیت تنظیم گردید' },
    { enterValidName: 'لطفاً نام درست را وارد نمایید' },
    { enterValidEmail: 'لطفاً ایمیل درست را وارد نمایید' },
    { enterValidMobile: 'لطفاً شماره تماس درست را وارد نمایید' },
    { selectCity: 'لطفاً شهر را انتخاب کنید' },
    { selectGrade: 'لطفاً صنف را انتخاب کنید' },
    { stateNotAvailable: 'ایالات موجود نیست' },
    { boardNotAvailable: 'نصاب موجود نیست' },
    { noSubjects: '!موضوع یافت نشد' },
    { noQuestions: '!سوالی یافت نشد' },
    { noQuestionPaper: "!ورق امتحان یافت نشد" },
    { noChapter: '!فصل یافت نشد' },
    { noTopic: '!موضوع یافت نشد' },
    { noGrades: '!صنف یافت نشد' },          
    { noNotes: '!متن یافت نشد' },
    { noMockTest: '!ورق سوالات آزمایشی یافت نشد' },
    { noTest: '!سوال آزمایشی یافت نشد' },
    { number1: '9494843456' },
    { number2: '08912702222' },
    { emailID: 'support@smartstepup.com' },
    { emailSubject: 'Inquiry from MyTeacher' },
    { webSite: 'www.smartstepup.com' },

    { noLanguage: '!زبان دریافت نگردید' },
    { submitQuiz: 'آیا مطمئن به درج نمودن ارزیابی هستید؟' },
    { timeUp: 'وقت شما ختم است! لطفاً جوابات خود را تسلیم نمایید' },
    { otpMsg1: 'ما کود عبور را برای شما ارسال کرده ایم به' },
    { otpMsg2: 'و' },
    { selectState: 'لطفاً نصاب تعلیمی تان را انتخاب نمایید' },
    { selectBoard: 'لطفاً بورد را انتخاب کنید' },
    { noNotification: 'تذکر جدید وجود ندارد' },
    { inviteYourFriend: 'دوست تان را به ثبت نام دعوت نمایید' },
    { installApp: 'دوستانتان برنامه را نصب نمایند' },
    { enjoyLearning: 'از دوره آموزشی لذت ببرید' },

    { completePreTest: 'ببخشید! ابتداء باید امتحان قبل از درس را تکمیل نمایید' },
    { beginTest: 'شما در حال شروع امتحان هستید' },
    { youWillHave: 'بعد از شروع، شما' },
    { finishTest: '10دقیقه تا پایان امتحان وقت خواهید داشت' },
    { notGraded: 'نظر به این امتحان درجه بندی صورت نمی گیرد' },
    { completePostTest: 'شما در حال شروع امتحان بعد از درس هستید' },
    { gradedTest: 'نظر به این امتحان درجه بندی صورت میگیرد' },
    { scoreIs: ':امتیاز شما' },
    { tryAgain: 'آیا می خواهید دوباره امتحان نمایید؟' },
    { testAgain: 'شما می توانید دوباره امتحان دهید' },
    { highestScore: 'ما بلند ترین امتیاز شما را حفظ خواهیم نمود' },
    { areYouReady: 'آیا آماده به شروع امتحان هستید ؟' },
    { correctAns: 'جواب شما درست است' },
    { incorrectAns: 'جواب شما اشتباه است' },
]

export default { MESSAGE_DA };